### ISSUE TITLE
Question: performance?

### ISSUE THREAD

**Issue by gytisgreitai** [mappedinn/kubernetes-nfs-volume-on-gke#4]
Hi, are you using this in production? Have you done some benchmarks, fine-tuned something?

**Comment by lvnilesh** [comment]
I just deployed this in a staging area. this seems to save money on small use cases compared to https://cloud.google.com/launcher/docs/single-node-fileserver

I tested with really simple dd based tests.

What tests do you suggest before entering production?

**Comment by gytisgreitai** [comment]
It all depends on your workload. What I'm interested in is how this would behave with ~100 clients constantlyreading/writing small files 5-15kb. What would the load on the nfs-server server.

What dd based tests did your perform? How large is your GCE disk?

Edit:

and what about nfs-server making more HA? Can i have two of those, how would they work?

**Comment by lvnilesh** [comment]
Cost of running:
This is poor mans ($) NFS solution. I am using a 200GB external persistent SSD which I snapshot periodically. I carve out PV using NFS backed by that SSD and PVC mount them as ReadWriteMany. The next better solution ($$) would be high-performing multi-disk ZFS backed single box n1-highmem-8 NFS filer https://cloud.google.com/launcher/docs/single-node-fileserver but still not HA. An HA solution ($$$) would be glusterfs based https://github.com/rimusz/glusterfs-gce and that would need three machines - each in a different zone within a region.

Performance:
This needs thorough testing for perf but I don't expect HA or blazing perf. I have attempted https://www.cyberciti.biz/faq/howto-linux-unix-test-disk-performance-with-dd-command/ but need to do more testing. my load is mostly small file reads not much write activity.

I am looking for ideas for refinement without going HA route while keeping NFS storage spend below $100 per month.

**Comment by lvnilesh** [comment]
With prelim load testing, this is working out to be a good poor man's NFS solution.
